# prod
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "users-myappnamexx-prod"
  description: "users-myappnamexx-prod"
  tags:
    - sx-cnp-oss
    - template
    - kargo
    - metalstack
    - kubex
  links:
    - url: http://users-myappnamexx-prod.lab.suxessit.k8s.cloud.uibk.ac.at
      title: Prod Instance of users-myappnamexx
      icon: web
  annotations:
    github.com/project-slug: suxess-it/users-myappnamexx
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=myappnamexx-prod'
    argocd/app-namespace: adn-users
    argocd/app-name: myappnamexx-prod
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.lab.suxessit.k8s.cloud.uibk.ac.at/project/users-myappnamexx-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.lab.suxessit.k8s.cloud.uibk.ac.at/d/a87fb0d919ec0ea5f6543124e16c42a5/kubernetes-compute-resources-namespace-workloads?orgId=1&refresh=10s&var-datasource=default&var-cluster=sx-loki&var-namespace=users-myappnamexx-prod&var-type=All"
spec:
  type: service
  lifecycle: prod
  owner: "users"
  system: myappnamexx
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: users-myappnamexx
---
#qa
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "users-myappnamexx-qa"
  description: "users-myappnamexx-qa"
  tags:
    - sx-cnp-oss
    - template
    - kargo
    - metalstack
    - kubex
  links:
    - url: http://users-myappnamexx-qa.lab.suxessit.k8s.cloud.uibk.ac.at
      title: QA Instance of users-myappnamexx
      icon: web
  annotations:
    github.com/project-slug: suxess-it/users-myappnamexx
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=myappnamexx-qa'
    argocd/app-namespace: adn-users
    argocd/app-name: myappnamexx-qa
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.lab.suxessit.k8s.cloud.uibk.ac.at/project/users-myappnamexx-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.lab.suxessit.k8s.cloud.uibk.ac.at/d/a87fb0d919ec0ea5f6543124e16c42a5/kubernetes-compute-resources-namespace-workloads?orgId=1&refresh=10s&var-datasource=default&var-cluster=sx-loki&var-namespace=users-myappnamexx-qa&var-type=All"
spec:
  type: service
  lifecycle: qa
  owner: "users"
  system: myappnamexx
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: users-myappnamexx
---
# test
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "users-myappnamexx-test"
  description: "users-myappnamexx-test"
  tags:
    - sx-cnp-oss
    - template
    - kargo
    - metalstack
    - kubex
  links:
    - url: http://users-myappnamexx-test.lab.suxessit.k8s.cloud.uibk.ac.at
      title: Test Instance of users-myappnamexx
      icon: web
  annotations:
    github.com/project-slug: suxess-it/users-myappnamexx
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=myappnamexx-test'
    argocd/app-namespace: adn-users
    argocd/app-name: myappnamexx-test
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.lab.suxessit.k8s.cloud.uibk.ac.at/project/users-myappnamexx-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.lab.suxessit.k8s.cloud.uibk.ac.at/d/a87fb0d919ec0ea5f6543124e16c42a5/kubernetes-compute-resources-namespace-workloads?orgId=1&refresh=10s&var-datasource=default&var-cluster=sx-loki&var-namespace=users-myappnamexx-test&var-type=All"
spec:
  type: service
  lifecycle: test
  owner: "users"
  system: myappnamexx
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: users-myappnamexx
---
# main, at the end of catalog-info.yaml so that register link is on main component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "users-myappnamexx"
  description: "users-myappnamexx"
  tags:
    - sx-cnp-oss
    - template
    - kargo
    - metalstack
    - kubex
  links:
    - url: https://argocd.lab.suxessit.k8s.cloud.uibk.ac.at/applications/adn-users/users-myappnamexx?resource=
      title: ArgoCD Application Information of users-myappnamexx
      icon: web
  annotations:
    github.com/project-slug: suxess-it/users-myappnamexx
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=users-myappnamexx'
    argocd/app-namespace: adn-users
    argocd/app-name: users-myappnamexx
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.lab.suxessit.k8s.cloud.uibk.ac.at/project/users-myappnamexx-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
  #  grafana/overview-dashboard: "https://grafana.lab.suxessit.k8s.cloud.uibk.ac.at/d/a87fb0d919ec0ea5f6543124e16c42a5/kubernetes-compute-resources-namespace-workloads?orgId=1&refresh=10s&var-datasource=default&var-cluster=sx-loki&var-namespace=users-myappnamexx-prod&var-type=All"
spec:
  type: service
  lifecycle: experimental
  owner: "users"
  system: myappnamexx
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
---
